/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args)
    {
        List<Chapitre> chapitresAlice = new ArrayList<>();
        Chapitre chap1 = new Chapitre("Introduction", new String[]{"intro1", "intro2"});
        Chapitre chap2 = new Chapitre("Patrons", new String[]{"patrons1", "patrons2","patrons3"});
        Chapitre chap3 = new Chapitre("Anti-Patrons", new String[]{"apatrons1", "apatrons2"});
        Chapitre chap4 = new Chapitre("Conclusion", new String[]{"conc1"});
        chapitresAlice.add(chap1);
        chapitresAlice.add(chap2);
        chapitresAlice.add(chap3);
        chapitresAlice.add(chap4);
        Mémoire mémoireAlice = new Mémoire("Patrons et Anti-Patrons",chapitresAlice);

        System.out.println(mémoireAlice.getTaille());
    }
}
